name: env
channels:
  - defaults
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - gcc_linux-64
  - libgcc
  - pip 
  - astropy
  - cudatoolkit=11
  - cudnn==8
  - cython
  - h5py
  - intervaltree
  - joblib
  - matplotlib
  - natsort
  - networkx
  - numpy
  - packaging
  - pandas
  - pillow
  - pybedtools
  - pybigwig
  - pysam
  - python=3.8
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tabulate
  - samtools
  - bwa
  - bowtie2
  - kipoiseq==0.5.2
  - pip:
    - cooler
    - cooltools
    - tensorflow=2.5.0
    - dm-sonnet==2.0.0